apiVersion: apps/v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.tokenKey }}: {{ .Values.secret.secretValue | b64enc }}