# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: "ghcr.io"
  # repository: ghcr.io/evgenpavlyuchek
  repository: "evgenpavlyuchek/tbot"
  tag: "v1.0.8-606fb47"
  os: linux
  arch: amd64
secret:
  name: tbot
  tokenName: TELE_TOKEN
  tokenKey: token
  secretValue: TELE_TOKEN
securityContext:
  privileged: true
