# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: terr
  tag: "v1.0.7-a5e1123"
  arch: arm64
secret:
  name: tbot
  tokenName: TELE_TOKEN
  tokenKey: token
  secretValue: TELE_TOKEN
securityContext:
  privileged: true