# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "evgenpavlyuchek/tbot"
  tag: "v1.1.2-81068f4"
  os: linux
  arch: amd64
  # registry: "terr"
  # repository: "tbot"
secret:
  name: tbot
  tokenName: TELE_TOKEN
  tokenKey: token
  secretValue: TELE_TOKEN
otel:
  otelName: METRICS_HOST
  otelValue: collector:4317
securityContext:
  privileged: true